name: build and deploy the website

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: install packages
      run: npm i
    - name: build
      run: npm run build
    - name: deploy
      run: npm run deploy